/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CreateUser: typeof import('./src/components/CreateUser.vue')['default']
    CreateUserForm: typeof import('./src/components/CreateUserForm.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginView: typeof import('./src/components/LoginView.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    Page1: typeof import('./src/components/vehicleData/Page1.vue')['default']
    Page2: typeof import('./src/components/vehicleData/Page2.vue')['default']
    Page3: typeof import('./src/components/vehicleData/Page3.vue')['default']
    RegistrationLogs: typeof import('./src/components/vehicleData/RegistrationLogs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackbarProvider: typeof import('./src/components/SnackbarProvider.vue')['default']
    UserDetails: typeof import('./src/components/UserDetails.vue')['default']
    Search: typeof import('./src/components/vehicleData/Search.vue')['default']
    VehicleSummary: typeof import('./src/components/vehicleData/VehicleSummary.vue')['default']
  }
}
