/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/devices': RouteRecordInfo<'/devices', '/devices', Record<never, never>, Record<never, never>>,
    '/driver-license': RouteRecordInfo<'/driver-license', '/driver-license', Record<never, never>, Record<never, never>>,
    '/new-officer': RouteRecordInfo<'/new-officer', '/new-officer', Record<never, never>, Record<never, never>>,
    '/new-vehicle': RouteRecordInfo<'/new-vehicle', '/new-vehicle', Record<never, never>, Record<never, never>>,
    '/officer-overview': RouteRecordInfo<'/officer-overview', '/officer-overview', Record<never, never>, Record<never, never>>,
    '/ownership-change': RouteRecordInfo<'/ownership-change', '/ownership-change', Record<never, never>, Record<never, never>>,
    '/techical-check': RouteRecordInfo<'/techical-check', '/techical-check', Record<never, never>, Record<never, never>>,
    '/traffic-license': RouteRecordInfo<'/traffic-license', '/traffic-license', Record<never, never>, Record<never, never>>,
    '/vehicle-deregistration': RouteRecordInfo<'/vehicle-deregistration', '/vehicle-deregistration', Record<never, never>, Record<never, never>>,
    '/vehicles': RouteRecordInfo<'/vehicles', '/vehicles', Record<never, never>, Record<never, never>>,
  }
}
